### ISSUE TITLE
Frontend template not working inside StructBlock

### ISSUE THREAD

**Issue by andre-fuchs** [torchbox/wagtail-footnotes#12]
Hello,

I cannot get the frontend template working for a `RichTextBlockWithFootnotes` as part of a `Structblock`. It is working like a charm on its own or as part of a `ListBlock`, though. Imagine the following `StreamField`:

```python
body = StreamField([
    ('quote', StructBlock([
        ('author', CharBlock()),
        ('text', RichTextBlockWithFootnotes(features=['footnotes', ],)),
    ])),
])
```

The following template would not work for the `StructBlock`. It does work for `ListBlock` or stand-alone though.

```django
{% for block in page.body %}
    {% include_block block %}
{% endfor %}
{% include "wagtail_footnotes/includes/footnotes.html" %}
```

Also this more specific try to call `include_block` on the RichText sub-block does not work. It returns the unfiltered RichText, e.g. _"Lorem ipsum dolor sit amet[d93fa8]"_ and would not contribute to `page.footnotes_list`.

```django
{% for block in page.body %}
    {% if block.block_type == 'quote' %}
        {% include_block block.value.text %}
    {% endif %}        
{% endfor %}
{% include "wagtail_footnotes/includes/footnotes.html" %}
```

Best case scenario: documentation needs a little update to cover this use case. A `RichTextBlock` as part of `StructBlock` is pretty common, I guess. Not sure how to debug this. The `render` function(s) of the `RichTextBlockWithFootnotes` do not get called, do they?

Warmest,
André

**Comment by jafacakes2011** [comment]
Hi @andre-fuchs,

Apologies for taking so long to get to this.
I had a little dig through some of the projects I am using this on and I found exactly what you need:

Simply change `{% include_block block.value.text %}` to `{% include_block block.value.bound_blocks.text %}` and it should all work as you expect!

Please let me know if this works for you!

**Comment by andre-fuchs** [comment]
Amazing! This works for me. Thanks for getting back, @jafacakes2011!
I had no idea about this BoundBlock concept. [Here is some explanation](https://docs.wagtail.io/en/latest/advanced_topics/boundblocks_and_values.html#boundblocks-and-values) that might be helpful for other people stumbling over this issue.
