### ISSUE TITLE
Footnotes not numbering correctly & footnotesection not showing

### ISSUE THREAD

**Issue by MPE2016** [torchbox/wagtail-footnotes#3]
Hi there,

The most likely cause is that I haven't configured wagtail_footnotes properly, but I can't seem to find what I did wrong, so that's why I'm writing this post. If there is another place or person I can go to for support, please let know. 

I have followed the instruction for implementing wagtail_footnotes as well as possible. I added wagtail_footnotes to the installed apps section in my base.py, added the footnotes to urls.py, included a footnote section to the content_panels of the page I wanted to use footnotes on and changed RichTextBlock to RichTextBlockWithFootnotes. Lastly I added the footnotesection to the template. 

And in the CMS section it actually works. Sort of. I have the option to add a footnote, both as a section and in the Richtext editor. I can add a footnote in the "Add footnote" section, but from there it goes off the rails for me. I know it shows a unique number on the backend side of things, but when I view the page it shows the unique id-number too (without a link) and not a regular footnote number. 

Furthermore, the html section is not showing either. I'm sure it's me, but I just can't see what I'm doing wrong. Help is much appreciated.

Many thanks in advance,

All the best,

MPE

but I am running into two issues (probably related)

**Comment by jafacakes2011** [comment]
Hi @MPE2016, would you be able to provide a few things so that I can debug this further?

- Wagtail Version
- Screenshots of the data in Wagtail Admin
- Screenshots of what the front end is outputting
- Any errors in the SJ Console

I have a feeling this might be something to do with the template or JS

**Comment by MPE2016** [comment]
Hi Jafacakes2011,

I'd be glad to.

Wagtail Version: 3.1.1

Admin Richtext Editor with footnotes:
![afbeelding](https://user-images.githubusercontent.com/15818884/95750307-3dbb0e80-0c9d-11eb-9483-8e1183a864a9.png)

Admin Footnotesection:
![afbeelding](https://user-images.githubusercontent.com/15818884/95750376-562b2900-0c9d-11eb-82dc-92da0ef2327f.png)

Frontend footnote. It returns the ID number and not the footnotenumber (should be [1]):
![afbeelding](https://user-images.githubusercontent.com/15818884/95750422-68a56280-0c9d-11eb-9c83-9aa12015fc05.png)

The List of footnotes generated by including footnotes.html in a template shows up nowhere. I included it in a template of a blogpage:
![afbeelding](https://user-images.githubusercontent.com/15818884/95750688-ccc82680-0c9d-11eb-8bfa-9420a0e8f84d.png)

These are the only errors in my JS console. Some of it is in Dutch, but I think you'll get the idea :
![afbeelding](https://user-images.githubusercontent.com/15818884/95750777-e9fcf500-0c9d-11eb-8103-1cd78a5e7f20.png)

That's about it. Should you have any questions, feel free to ask!

All the best,

MPE

**Comment by jafacakes2011** [comment]
I have managed to create this issue locally by Switching my `RichTextBlockWithFootnotes` back to a normal `RichTextBlock`.
Can you confirm that all the RichTextBlocks have been updated to `wagtail_footnotes.blocks.RichTextBlockWithFootnotes`?

**Comment by jafacakes2011** [comment]
Here is my example page that I tested with:

```python
from django.db import models

from wagtail.core import blocks
from wagtail.core.models import Page
from wagtail.core.fields import StreamField
from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.images.blocks import ImageChooserBlock
from wagtail_footnotes.blocks import RichTextBlockWithFootnotes

from wagtail.admin.edit_handlers import InlinePanel


class HomePage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', RichTextBlockWithFootnotes()),
        ('image', ImageChooserBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
        InlinePanel("footnotes", label="Footnotes")
    ]
```

Changing my `paragraph` block in the streamfield to a `RichTextBlock` recreates your issue.

**Comment by MPE2016** [comment]
I think I have found the culprit. It wasn't the use of either `RichTextBlock` of `RichTextBlockWithFootnotes`. I almost always explicitly define a template, and I also had done so in this one, like so (example code):
```
class RichTextBlockWithFootnotes(RichTextBlockWithFootnotes):

    class Meta:
        template = "streams/richtext_block.html"
        icons = "edit"
        label = "Richtext block met voetnoten"

Once I remode the template variable from Meta, things began working as expected. 
Now it is using the Richtext template from wagtail core. I can change that to my liking of course, but I would rather use my own template. Is that a possibility?
```

**Comment by jafacakes2011** [comment]
It should be possible to use your own template, maybe start with a custom template that is a copy of the Wagtail core template then strip out/change things as needed.

**Comment by MPE2016** [comment]
Ok. I'm pretty sure that that's not working, at least not on my side of things. As I wrote in my previous post; if I define a template it returns the footnotes as shown in my initial post. When removed, it starts working. 

I actually tried using the template from Wagtail core, which looks like this:
`{{ html|safe }}`

If I create a selfmade template with this code neither the text nor the footnotesection show up at all.

**Comment by MPE2016** [comment]
Uhm yeah  :smile: 

The problem is that I don't think I would be able to fix this code on my own. I mean I do know some python, but just not enough for this kind of thing. 

To be honest, I don't even really know what the problem is. In And I wouldn't know where to start. Is this a fix that needs to be applied to wagtail core, wagtail_footnotes, or perhaps both? 

I totally understand that it would take somebody's time - which would perhaps even mean yours - were this to be fixed. You are probably working on something else and have no need for footnotes in your wagtail projects :smile:. 

The way I see it there are four options:

- I learn enough Python and Wagtail to fix this myself. Which I'd love to, but I still don't think I'd be able to fix this anytime soon, and I wouldn't know where to start exactly.
- Ask someone else to do it. Do you perhaps know someone who would be able to fix this?
- Just accept the fact that for the time being it is not possible to use your own templates for wagtail_footnotes and edit the template from wagtail core. 
- Dismiss the idea of using wagtail_footnotes altogether, at least for now. 

The latter I would really find a pity, because I think it is such an elegant idea. 

Or perhaps you have a different solution?

**Comment by zerolab** [comment]
@MPE2016 can you try #4

**Comment by MPE2016** [comment]
> @MPE2016 can you try #4 and see if that works for you?

Hi @zerolab, thanks for the fix. I just tested it, and it seems to have done the trick! Thanks a million! If this ever needs any more testing, please do not hesitate to contact me!

**Comment by jafacakes2011** [comment]
I'm merging https://github.com/torchbox/wagtail-footnotes/pull/4 and making a new release `0.4.0`
