### ISSUE TITLE
Support Wagtail 4

### ISSUE THREAD

**Issue by 2qxtx** [torchbox/wagtail-footnotes#41]
Hello. Do you plan to support Wagtail 4 anytime soon? Thank you.

**Comment by zerolab** [comment]
We don't constrain the Django version in wagtail-footnotes.
So it should work. If you're seeing issues with that, please provide more context, tracebacks etc

**Comment by 2qxtx** [comment]
Apologies, I think I meant to say Wagtail 4 as opposed to Django 4.

When I install Wagtail, version: 3.0.3 is fetched. So I tried installing via `git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail`, but I get the following error:

```
ERROR: Cannot install -r /app/requirements/base.txt (line 11), -r /app/requirements/base.txt (line 6), -r /app/requirements/base.txt (line 9) and wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail) because these package versions have conflicting dependencies.

The conflict is caused by:
     The user requested wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail)
     wagtail-footnotes 0.8.1 depends on wagtail<4.0 and >=2.15
     The user requested wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail)
     wagtail-footnotes 0.7.0 depends on wagtail<3 and >=2.5
     The user requested wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail)
     wagtail-footnotes 0.6.0 depends on wagtail<3 and >=2.5
     django-tailwind 3.1.1 depends on django>=2.2.25
     wagtail 4.0 depends on Django<4.2 and >=3.2
     wagtail-footnotes 0.5.0 depends on Django<3.2 and >=2.2
     django-tailwind 3.1.1 depends on django>=2.2.25
     wagtail 4.0 depends on Django<4.2 and >=3.2
     wagtail-footnotes 0.4.1 depends on Django<3.2 and >=2.2
     django-tailwind 3.1.1 depends on django>=2.2.25
     wagtail 4.0 depends on Django<4.2 and >=3.2
     wagtail-footnotes 0.4.0 depends on Django<3.2 and >=2.2
     django-tailwind 3.1.1 depends on django>=2.2.25
     wagtail 4.0 depends on Django<4.2 and >=3.2
     wagtail-footnotes 0.3.1 depends on Django<3.2 and >=2.2
     The user requested wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail)
     wagtail-footnotes 0.3.0 depends on wagtail<2.10 and >=2.5
     The user requested wagtail 4.0 (from git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail)
     wagtail-footnotes 0.2.0 depends on wagtail<2.10 and >=2.5
```

My requirements file is as follows:

```
boto3
cookiecutter
crispy-tailwind
django-cors-headers
django-storages
django-tailwind==3.1.1
Pillow
sentry-sdk
# wagtail
git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail
wagtail-footnotes
wagtail-metadata
wagtailcodeblock
wagtailmedia
wagtailfontawesome
Wand
```

**Comment by zerolab** [comment]
There are multiple issues here. your requirements.txt should specify versions, or version constraints.

For example: having just `wagtail` means whenever there is big new version you will get that. and things will likely break because of various deprecations. Case in point, you mention Wagtail 3.0.3, but the log shows clearly it tries to install Wagtail 4.0, but there's a clash with wagtail-footnotes as it is currently constrained to <4.0

**Comment by zerolab** [comment]
> So I tried installing via `git+https://github.com/wagtail/wagtail@v4.0#egg=wagtail`
oh, I missed that you went specifically for Wagtail 4.

#39 bumps the Wagtail version restriction. In theory could specify `git+https://github.com/GreenLightGo/wagtail-footnotes/@wagtail-4.0#egg=wagtail-footnotes` and test it and perhaps report any issues

**Comment by 2qxtx** [comment]
> #39 bumps the Wagtail version restriction. In theory could specify `git+https://github.com/GreenLightGo/wagtail-footnotes/@wagtail-4.0#egg=wagtail-footnotes` and test it and perhaps report any issues

This worked nicely, thank you!

**Comment by jsma** [comment]
@2qxtx I'm sorry if you were relying on my branch which I just deleted. I didn't see this closed thread before deleting it. My fork was not sufficient as you probably noticed when you submitted #43. I'll do my best to review #42 and do what I can to contribute to a releasable fix, since this is impacting a project of mine as well.

**Comment by 2qxtx** [comment]
@jsma. No worries and thanks for letting me know. I'm using Wagtail 4 and, as you say, I was relying on your branch. I now find myself in a bit of a pickle as I can't run my project in development without pip installing your branch, nor can I downgrade to an earlier versions of wagtail-footnotes as they rely on Wagtail 3 and below. Do you know how I can remove references to wagtail footnotes (e.g., in my migration files which `import wagtail_footnotes.blocks`), without affecting other data held in RichTextBlocks? So basically, I would like to revert back to using Wagtail's native RichTextBlocks for the time being.

**Comment by jsma** [comment]
We're running #42 in production and so far we haven't had any issues. You can install that branch by adding this to your requirements, while we wait for a proper release:

```
wagtail-footnotes @ git+https://github.com/torchbox/wagtail-footnotes@93131b4b230ea59c5357476576d3551dffe8f20d
```

**Comment by 2qxtx** [comment]
Thank you. That solved my problem nicely!

**Comment by zerolab** [comment]
@2qxtx @jsma https://github.com/torchbox/wagtail-footnotes/releases/tag/0.9.0 is out with the full Wagtail 4 support
