### ISSUE TITLE
No footnotes in "Choose a footnote" modal

### ISSUE THREAD

**Issue by 2qxtx** [torchbox/wagtail-footnotes#43]
Hello,

I am running wagtail version 4.0.2 and wagtail-footnotes version 0.8.1.

I am able to save footnotes:
<img width="900" alt="Screen Shot 2022-09-28 at 3 01 04 PM" src="https://user-images.githubusercontent.com/78832587/192700639-5daec98f-10f6-4a9c-a69e-72035085ee09.png">

But when it comes to choosing a footnote from the "Choose a footnote" modal that appears after clicking the "footnotes" icon in the richtext bar, there are no footnotes to choose from:
<img width="1295" alt="Screen Shot 2022-09-28 at 3 05 58 PM" src="https://user-images.githubusercontent.com/78832587/192700745-b8a58801-e94c-4deb-95de-734dcad3ebeb.png">

How might I go about solving this problem?

**Comment by jsma** [comment]
It looks like there is work in #42 that may address this.

**Comment by jsma** [comment]
Now that Wagtail 4 support is [official](https://github.com/torchbox/wagtail-footnotes/issues/41#issuecomment-1279712664), I believe this can be closed.

**Comment by zerolab** [comment]
Good shout!
