### ISSUE TITLE
New migration needed for Wagtail 6.2

### ISSUE THREAD

**Issue by willbarton** [torchbox/wagtail-footnotes#71]
Wagtail 6.2 [alters the `Locale` model on `TranslatableMixin`, adding a `verbose_name`](https://github.com/wagtail/wagtail/commit/ad95e0a9910e73fe10b8a5cf0a278305446aad7b#diff-5696db3154db4f1f279fda164ea702d159c60824574fc693ae09b5f7e7a2467e). Because [`Footnote` inherits from `TranslatableMixin`](https://github.com/torchbox/wagtail-footnotes/blob/main/wagtail_footnotes/models.py#L13), it needs a new migration generated for Wagtail 6.2.

That's easy enough to generate, and I could do so and then PR the change, but I'm not sure how you all would want to handle the backward-incompatibility that would create with Wagtail < 6.1.

Currently, this is a blocker for our 6.2 upgrade as we have a required check in CI that runs `makemigrations --dry-run --check` to ensure there are no missing migrations.

**Comment by zerolab** [comment]
I think we could conditionally do


```py
# wagtail_footnotes/models.py
from wagtail import VERSION as WAGTAIL_VERSION

...

if WAGTAIL_VERSION < (6, 2):
   Footnote._meta.get_field("locale").verbose_name = _("locale")
```

which should sort this. If you have the time to give it a try, it would fantastic

**Comment by willbarton** [comment]
Unfortunately that doesn't appear to fool Django's migration model state/audodetector, because it does an independent resolution of model field relations (I believe [that happens here](https://github.com/django/django/blob/main/django/db/migrations/state.py#L470-L478)) rather than it occurring after evaluation of this `models.py` file.

Long way to saying, Django still wants to generate a new migration with this operation:

```python
migrations.AlterField(
    model_name='footnote',
    name='locale',
    field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagt      ailcore.locale', verbose_name='locale'),
),
```

**Comment by gasman** [comment]
Could we wrap the AlterField operation in a version check?

```python
class Migration(migrations.Migration):

    dependencies = [...]

    operations = []
    if WAGTAIL_VERSION >= (6, 1):
        operations.append(
            migrations.AlterField(
                model_name='footnote',
                name='locale',
                field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            )
        )
```

This way, the final state that Django arrives at from evaluating the migrations will match the real model state, whichever Wagtail version it's run under. And if the `verbose_name` is indeed the only change to the model, then there'll be no change to the database schema, so it doesn't matter whether this migration gets run under 6.0 or 6.1.

I seem to remember us doing something similar in Wagtail itself, possibly as a result of django-taggit making a similarly minor change in a point release.
